#!/usr/bin/env python3
"""Paper Deep Parser — Knowledge Card Markdown Parser.

Extracts structured JSON fields from card.md files generated by
read-arxiv-paper. This is the deterministic tool layer for the
paper-deep-parser Skill.

The Agent (via SKILL.md) orchestrates:
  1. For each paper, create an independent Session via sessions_spawn
  2. Trigger read-arxiv-paper to generate card.md
  3. Call this script to extract structured JSON from card.md

Extracted Fields:
  - sub_field: Research sub-field classification
  - ID_paradigm: Item ID/representation paradigm
  - item_tokenizer: Tokenization method for items
  - baselines_compared: List of baseline methods compared
  - transferable_techniques: Techniques transferable to other work
  - inspiration_ideas: Ideas inspired by the paper

Usage:
    # Parse a single card.md file
    python card_parser.py --card-path /path/to/card.md --arxiv-id 2305.05065

    # Parse all cards for a pipeline run (batch mode)
    python card_parser.py --run-id {run_id}

    # Parse with explicit output path
    python card_parser.py --card-path /path/to/card.md --output /path/to/output.json
"""

import argparse
import json
import logging
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# Standard path injection for paper-agent common modules
_PAPER_AGENT_ROOT = Path(os.environ.get("PAPER_AGENT_ROOT", str(Path(__file__).resolve().parent.parent)))
if str(_PAPER_AGENT_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(_PAPER_AGENT_ROOT / "scripts"))

from common.config_loader import load_profile
from common.path_manager import PathManager

logger = logging.getLogger("paper_agent.card_parser")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

# Default value for fields that cannot be reliably extracted
NA = "N/A"


# ═══════════════════════════════════════════════════════════════════════════════
# Markdown Section Extraction
# ═══════════════════════════════════════════════════════════════════════════════


def extract_sections(card_text: str) -> Dict[str, str]:
    """Extract Markdown sections from card.md content.

    Splits a Markdown document by heading levels (##, ###), returning
    a dict mapping heading text (lowercased, stripped) → section body.

    Args:
        card_text: Full text content of card.md.

    Returns:
        Dict mapping section heading (lowercase) to section body text.
    """
    sections: Dict[str, str] = {}
    current_heading = ""
    current_body: List[str] = []

    for line in card_text.split("\n"):
        heading_match = re.match(r"^(#{1,4})\s+(.+)$", line)
        if heading_match:
            # Save previous section
            if current_heading:
                sections[current_heading] = "\n".join(current_body).strip()
            current_heading = heading_match.group(2).strip().lower()
            current_body = []
        else:
            current_body.append(line)

    # Save last section
    if current_heading:
        sections[current_heading] = "\n".join(current_body).strip()

    return sections


def extract_list_items(text: str) -> List[str]:
    """Extract list items from Markdown text (both - and * bullets).

    Args:
        text: Markdown text potentially containing bullet lists.

    Returns:
        List of extracted item texts (stripped of bullet markers).
    """
    items = []
    for line in text.split("\n"):
        line = line.strip()
        match = re.match(r"^[-*+]\s+(.+)$", line)
        if match:
            items.append(match.group(1).strip())
        # Also handle numbered lists
        match = re.match(r"^\d+[.)]\s+(.+)$", line)
        if match:
            items.append(match.group(1).strip())
    return items


def extract_bold_value(text: str, key: str) -> Optional[str]:
    """Extract value from **Key**: Value pattern in Markdown.

    Args:
        text: Markdown text to search.
        key: Bold key to look for (case-insensitive).

    Returns:
        Extracted value or None if not found.
    """
    pattern = rf"\*\*{re.escape(key)}\*\*\s*[:：]\s*(.+)"
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# Field-Specific Extractors
# ═══════════════════════════════════════════════════════════════════════════════


def extract_sub_field(sections: Dict[str, str], full_text: str) -> str:
    """Extract research sub-field classification.

    Looks for sub-field in common section headings and metadata patterns.
    """
    # Try direct metadata extraction
    for key in ["sub_field", "sub-field", "subfield", "research area",
                "research direction", "field", "category", "track"]:
        val = extract_bold_value(full_text, key)
        if val:
            return val

    # Look in metadata section
    for heading_key in ["metadata", "basic information", "paper info",
                        "overview", "classification"]:
        if heading_key in sections:
            for key in ["sub_field", "field", "direction", "area", "track"]:
                val = extract_bold_value(sections[heading_key], key)
                if val:
                    return val

    return NA


def extract_id_paradigm(sections: Dict[str, str], full_text: str) -> str:
    """Extract item ID/representation paradigm.

    Relevant for generative recommendation papers (TIGER, OneRec style).
    """
    for key in ["id paradigm", "id_paradigm", "item representation",
                "item id", "id generation", "semantic id"]:
        val = extract_bold_value(full_text, key)
        if val:
            return val

    # Search in methodology/approach sections
    for heading_key in ["methodology", "approach", "method", "core method",
                        "technical approach", "key innovation"]:
        if heading_key in sections:
            text = sections[heading_key]
            if "semantic id" in text.lower():
                return "Semantic ID"
            if "rq-vae" in text.lower():
                return "RQ-VAE"
            if "collaborative id" in text.lower():
                return "Collaborative ID"

    return NA


def extract_item_tokenizer(sections: Dict[str, str], full_text: str) -> str:
    """Extract tokenization method for items."""
    for key in ["item_tokenizer", "item tokenizer", "tokenizer", "tokenization",
                "item tokenization", "tokenization method"]:
        val = extract_bold_value(full_text, key)
        if val:
            return val

    # Search in methodology sections
    for heading_key in ["methodology", "approach", "method", "technical details"]:
        if heading_key in sections:
            text = sections[heading_key].lower()
            if "rq-vae" in text:
                return "RQ-VAE"
            if "vq-vae" in text:
                return "VQ-VAE"
            if "bpe" in text:
                return "BPE"
            if "sentencepiece" in text:
                return "SentencePiece"

    return NA


def extract_baselines(sections: Dict[str, str], full_text: str) -> List[str]:
    """Extract list of baseline methods compared in experiments."""
    # Look for experiment/baseline sections
    for heading_key in ["baselines", "baseline", "compared methods",
                        "comparison methods", "experiments",
                        "experimental setup", "experimental results"]:
        if heading_key in sections:
            items = extract_list_items(sections[heading_key])
            if items:
                return items

    # Try extracting from bold key pattern
    for key in ["baselines", "baseline", "compared methods", "baselines_compared"]:
        val = extract_bold_value(full_text, key)
        if val:
            # Split comma-separated baselines
            return [b.strip() for b in re.split(r"[,;，；]", val) if b.strip()]

    return [NA]


def extract_transferable_techniques(sections: Dict[str, str], full_text: str) -> List[str]:
    """Extract techniques that could be transferred to other research."""
    # Look for relevant sections
    for heading_key in ["transferable techniques", "key contributions",
                        "contributions", "takeaways", "key insights",
                        "novel contributions", "main contributions"]:
        if heading_key in sections:
            items = extract_list_items(sections[heading_key])
            if items:
                return items

    for key in ["transferable_techniques", "transferable techniques",
                "key techniques", "contributions"]:
        val = extract_bold_value(full_text, key)
        if val:
            return [t.strip() for t in re.split(r"[,;，；]", val) if t.strip()]

    return [NA]


def extract_inspiration_ideas(sections: Dict[str, str], full_text: str) -> List[str]:
    """Extract research ideas inspired by the paper."""
    for heading_key in ["inspiration", "ideas", "inspiration ideas",
                        "future work", "research ideas", "potential extensions",
                        "possible improvements"]:
        if heading_key in sections:
            items = extract_list_items(sections[heading_key])
            if items:
                return items

    for key in ["inspiration_ideas", "inspiration", "future directions",
                "research ideas"]:
        val = extract_bold_value(full_text, key)
        if val:
            return [i.strip() for i in re.split(r"[,;，；]", val) if i.strip()]

    return [NA]


def extract_title(sections: Dict[str, str], full_text: str) -> str:
    """Extract paper title from card.md."""
    # Try first heading
    match = re.match(r"^#\s+(.+)", full_text)
    if match:
        return match.group(1).strip()

    for key in ["title", "paper title"]:
        val = extract_bold_value(full_text, key)
        if val:
            return val

    return NA


# ═══════════════════════════════════════════════════════════════════════════════
# Main Parse Function
# ═══════════════════════════════════════════════════════════════════════════════


def parse_card(card_path: str, arxiv_id: str = "") -> Dict[str, Any]:
    """Parse a knowledge card Markdown file into structured JSON.

    Args:
        card_path: Path to the card.md file.
        arxiv_id: arXiv ID of the paper. If empty, attempts extraction
            from file path or content.

    Returns:
        Structured dict with all extracted fields. Fields that cannot
        be reliably extracted are filled with "N/A".
    """
    card_file = Path(card_path)
    if not card_file.exists():
        logger.error("Card file not found: %s", card_path)
        return _empty_result(arxiv_id, card_path, error="Card file not found")

    try:
        card_text = card_file.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        logger.error("Failed to read card file: %s — %s", card_path, e)
        return _empty_result(arxiv_id, card_path, error=str(e))

    if not card_text.strip():
        logger.warning("Card file is empty: %s", card_path)
        return _empty_result(arxiv_id, card_path, error="Empty card file")

    # Extract arxiv_id from path if not provided
    if not arxiv_id:
        arxiv_id = _extract_arxiv_id_from_path(card_path)

    sections = extract_sections(card_text)

    result = {
        "arxiv_id": arxiv_id,
        "title": extract_title(sections, card_text),
        "sub_field": extract_sub_field(sections, card_text),
        "ID_paradigm": extract_id_paradigm(sections, card_text),
        "item_tokenizer": extract_item_tokenizer(sections, card_text),
        "baselines_compared": extract_baselines(sections, card_text),
        "transferable_techniques": extract_transferable_techniques(sections, card_text),
        "inspiration_ideas": extract_inspiration_ideas(sections, card_text),
        "card_path": str(card_file.resolve()),
        "parse_success": True,
    }

    # Count how many fields were successfully extracted (not N/A)
    na_count = sum(
        1 for k, v in result.items()
        if k not in ("arxiv_id", "card_path", "parse_success", "title")
        and (v == NA or v == [NA])
    )
    result["fields_extracted"] = 6 - na_count
    result["fields_total"] = 6

    logger.info(
        "Parsed card for %s: %d/%d fields extracted",
        arxiv_id, result["fields_extracted"], result["fields_total"],
    )
    return result


def _empty_result(arxiv_id: str, card_path: str, error: str = "") -> Dict[str, Any]:
    """Return an empty result dict with all fields set to N/A."""
    return {
        "arxiv_id": arxiv_id,
        "title": NA,
        "sub_field": NA,
        "ID_paradigm": NA,
        "item_tokenizer": NA,
        "baselines_compared": [NA],
        "transferable_techniques": [NA],
        "inspiration_ideas": [NA],
        "card_path": card_path,
        "parse_success": False,
        "parse_error": error,
        "fields_extracted": 0,
        "fields_total": 6,
    }


def _extract_arxiv_id_from_path(card_path: str) -> str:
    """Attempt to extract arxiv_id from the card file path.

    Looks for patterns like: .../2305.05065_tiger/card.md
    """
    parts = Path(card_path).parts
    for part in reversed(parts):
        match = re.match(r"(\d{4}\.\d{4,5})(?:v\d+)?(?:_|$)", part)
        if match:
            return match.group(1)
    return ""


# ═══════════════════════════════════════════════════════════════════════════════
# Batch Processing (for pipeline_runner.py integration)
# ═══════════════════════════════════════════════════════════════════════════════


def run_deep_parse(
    pm: PathManager,
    profile: Dict[str, Any],
) -> Dict[str, Any]:
    """Parse all selected papers for a pipeline run.

    Reads skill3_final_selection.json, finds card.md files in the
    research directory, and parses each one.

    Args:
        pm: PathManager for the current run.
        profile: Profile configuration.

    Returns:
        Statistics dict with parse results.
    """
    # Load final selection
    if not pm.skill3_final_selection.exists():
        logger.warning("Final selection not found: %s", pm.skill3_final_selection)
        return {"parsed_count": 0, "success_count": 0, "failed_count": 0}

    try:
        with open(pm.skill3_final_selection, "r", encoding="utf-8") as f:
            papers = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Failed to load final selection: %s", e)
        return {"parsed_count": 0, "success_count": 0, "failed_count": 0}

    pm.skill4_parsed_dir.mkdir(parents=True, exist_ok=True)

    parsed_count = 0
    success_count = 0
    failed_count = 0
    results = []

    research_dir = Path(
        profile.get("research_dir", str(_PAPER_AGENT_ROOT / "research"))
    )

    for paper in papers:
        arxiv_id = paper.get("arxiv_id", "")
        if not arxiv_id:
            continue

        # Try to find existing card.md
        card_path = _find_card_path(arxiv_id, research_dir)

        if card_path:
            result = parse_card(str(card_path), arxiv_id)
        else:
            # Card not yet generated — Agent needs to trigger read-arxiv-paper
            logger.info("No card.md found for %s — needs read-arxiv-paper", arxiv_id)
            result = _empty_result(
                arxiv_id, "",
                error="Card not found. Trigger read-arxiv-paper first.",
            )
            result["needs_reading"] = True

        # Save individual result
        output_path = pm.skill4_parsed_paper(arxiv_id)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, ensure_ascii=False)

        parsed_count += 1
        if result.get("parse_success"):
            success_count += 1
        else:
            failed_count += 1
        results.append(result)

    stats = {
        "parsed_count": parsed_count,
        "success_count": success_count,
        "failed_count": failed_count,
        "needs_reading": sum(1 for r in results if r.get("needs_reading")),
    }
    logger.info("Deep parse complete: %s", stats)
    return stats


def _find_card_path(arxiv_id: str, research_dir: Path) -> Optional[Path]:
    """Search for a card.md file for a given arxiv_id.

    Searches the research directory tree for card.md files whose
    parent directory name contains the arxiv_id.
    """
    papers_dir = research_dir / "papers"
    if not papers_dir.exists():
        return None

    # Search recursively for card.md in directories matching arxiv_id
    safe_id = arxiv_id.replace("/", "_")
    for card_file in papers_dir.rglob("card.md"):
        if safe_id in str(card_file.parent.name):
            return card_file

    # Also check cache directory
    cache_dir = research_dir / "cache" / safe_id
    card_in_cache = cache_dir / "card.md"
    if card_in_cache.exists():
        return card_in_cache

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# CLI Entry Point
# ═══════════════════════════════════════════════════════════════════════════════


def main():
    parser = argparse.ArgumentParser(
        description="Paper Deep Parser — Knowledge Card Markdown Parser"
    )
    parser.add_argument("--card-path", type=str, help="Path to card.md file")
    parser.add_argument("--arxiv-id", type=str, default="", help="arXiv paper ID")
    parser.add_argument("--output", type=str, default=None, help="Output JSON path")
    parser.add_argument("--run-id", type=str, default=None, help="Pipeline run ID (batch mode)")
    parser.add_argument("--profile", type=str, default=None, help="Path to profile.yaml")
    args = parser.parse_args()

    if args.run_id:
        # Batch mode: parse all papers for a run
        try:
            profile = load_profile(args.profile)
        except (FileNotFoundError, ValueError) as e:
            logger.error("Failed to load profile: %s", e)
            sys.exit(1)

        pm = PathManager(run_id=args.run_id)
        stats = run_deep_parse(pm=pm, profile=profile)
        result = {
            "step": "deep-parse",
            "status": "success",
            "run_id": pm.run_id,
            **stats,
            "message": (
                f"Parsed {stats['parsed_count']} papers: "
                f"{stats['success_count']} success, {stats['failed_count']} failed, "
                f"{stats.get('needs_reading', 0)} need read-arxiv-paper."
            ),
        }
        print(json.dumps(result, indent=2, ensure_ascii=False))

    elif args.card_path:
        # Single file mode
        result = parse_card(args.card_path, args.arxiv_id)

        if args.output:
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(result, f, indent=2, ensure_ascii=False)
            logger.info("Result saved to %s", output_path)

        print(json.dumps(result, indent=2, ensure_ascii=False))

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
